blank_issues_enabled: false
contact_links:
  - name: RapidFire AI Documentation
    url: https://github.com/RapidFireAI/rapidfireai#readme
    about: Please check our documentation before opening an issue
  - name: Community Discussions
    url: https://github.com/RapidFireAI/rapidfireai/discussions
    about: Ask questions and discuss ideas with the community
