name: Deploy to TestPyPI

on:
  push:
    tags:
      - 'test*'  # Trigger on test tags like test0.9.5, test1.0.0, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'rapidfireai/frontend/yarn.lock'

      - name: Install frontend dependencies
        run: |
          cd rapidfireai/frontend
          yarn install --frozen-lockfile

      - name: Build frontend
        run: |
          cd rapidfireai/frontend
          yarn build

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          rm -rf dist/ *.egg-info/ .eggs/
          python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN_SUPPORT_DEV }}
        run: |
          python -m twine upload --repository testpypi dist/* --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 30 